databases:
  - name: somerset-window-cleaning-db
    databaseName: somerset_window_cleaning
    plan: free
    
services:
  - type: web
    name: somerset-window-cleaning-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run migrate:deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: somerset-window-cleaning-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://your-frontend-domain.com # Update this with your actual frontend URL
      - key: EMAILJS_PUBLIC_KEY
        sync: false # Set in Render dashboard
      - key: EMAILJS_PRIVATE_KEY
        sync: false # Set in Render dashboard
      - key: EMAILJS_SERVICE_ID
        sync: false # Set in Render dashboard
      - key: EMAILJS_TEMPLATE_ID
        sync: false # Set in Render dashboard
      - key: RECAPTCHA_SECRET_KEY
        sync: false # Set in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true